### ISSUE TITLE
Validate that there can't be 2 unresolved deploy blocks for a given project

### ISSUE THREAD

**Issue by dleve123** [artsy/horizon#45]
Seems like a sensible validation

**Comment by joeyAghion** [comment]
I actually like how the current modeling allows multiple overlapping blocks. If there were 2 different obstacles to releasing, they should both be resolved before a release can happen.

**Comment by dleve123** [comment]
I dig that actually – the way the current API is designed, nothing would break if there are multiple unresolved API blocks. Closing.
